# Generated by Django 2.1.3 on 2019-08-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OneTeam', to='teams.Team', verbose_name='Первая команда')),
                ('two_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TwoTeam', to='teams.Team', verbose_name='Вторая команда')),
            ],
            options={
                'verbose_name': 'Тотал',
                'verbose_name_plural': 'Тотал',
            },
        ),
    ]
