# Generated by Django 2.1.3 on 2019-08-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_totals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_map', models.IntegerField(verbose_name='Время игры:')),
                ('kill_map', models.IntegerField(verbose_name='Убийств:')),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AddField(
            model_name='time_kill',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='teams.Team', verbose_name='Команда:'),
        ),
    ]
