# Generated by Django 2.1.3 on 2019-08-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190817_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time_kill',
            options={'verbose_name': 'Totals', 'verbose_name_plural': 'totals'},
        ),
    ]
