# Generated by Django 2.1.3 on 2019-08-17 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190817_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_kill',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='time_kill',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
